### ISSUE TITLE
ECHO columns might be shifting again?

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/USGS_Consumptive_Use#69]
I ran into this error -- using latest master: (in https://github.com/HARPgroup/USGS_Consumptive_Use/blob/master/Code/ECHO%20to%20VAHydro/ECHO_VAHydro_Import.R )

```
ECHO_Facilities <- sqldf(keep_permits)
Error: no such column: CWPPermitTypeDesc
```

**Comment by jmineva** [comment]
library(echor) #used to pull ECHO data

#shows a list of all fields and descriptions
echoWaterGetMeta()

As of 6/1/2020 - CWPPermitTypeDesc = 63

**Comment by jmineva** [comment]
Nice work, Rob!
