### ISSUE TITLE
adminreg variable undeclared in most recent version of the code ECHO_VAhydro_import.R

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/USGS_Consumptive_Use#78]
Hey guys, I need some help making sure that I am not getting crazy.  I am testing down to the function "permit_import()", but getting an error because "adminreg" data frame is not declared.  I see [with a github search of the code base](https://github.com/HARPgroup/USGS_Consumptive_Use/search?q=adminreg&unscoped_q=adminreg) that it is declared in the files "OldVersions/ImportCode_JK_COPY.R", and "examples/ImportCode_Kleiner.R", and even "Code/Old Versions/ImportCode_McCarthy.R", but there is not a declaration in the current version of ECHO_VAhydro_import.R. 

There is also a declaration for data frame "adminreg" commented out in ECHO_VAHydro_import.R from a commit that you guys did in January.  But, it was commented out so, not actually functioning.  This commented block of code then later got deleted during your 2.4.echo.jam push.

Thus, I just want to make sure that I am not refixing something that's already fixed, or to catch myself in case I managed to overwrite the code by accident or something?  I am doing very little coding here, but I *am* moving functions into R_functions.R as I test and tweak them (when needed) for readability.  So, it is possible that I killed something by accident, but I don't think so.

Otherwise, I am creating the adminreg data frame with sqldf inside of the function "permit_import()", which is the first place in the existing code that calls it.

**Comment by rburghol** [comment]
@jmineva - thanks, and nope, permit_REST() seems to work OK.  And so, permit_import() would seem to be redundant ... whcih makes me wonder why it's there.  But, this also gives me a clue to the error, I am wondering if the error is actually because the permit_import() is then trying to create a duplicate?  Anyhow, I am going to investigate whether or not we can comment out that section, or if we need to create permits later in the work flow (like maybe the first part of the code was for initial imports, and the latter part is for maintenance).  Onward -- I will report back.

**Comment by jmineva** [comment]
@rburghol Yeah, permit_import() is Morgan's original code. That can be deleted. I guess we didn't delete as we went so that we could have a reference for where we were in Morgan's code and follow along. Sorry this caused you so much confusion.
