### ISSUE TITLE
matched_switch() function to prevent duplicate facilities

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/USGS_Consumptive_Use#79]
@jdkleiner  and @jdkleiner - the matched_switch() function is farther down the code, and it is intended to prevent duplicate facilities from [a list of facilities](https://raw.githubusercontent.com/HARPgroup/USGS_Consumptive_Use/master/Code/Facility%20Matching/Runninglist_Matches.csv) that Morgan compiled that had certain matches -- i.e., all power plants and then a select group of larger commercial facilities (maybe others?).

Anyhow, I am thinking that this needs to be done *before* we create a facility, in other words, matched_switch() function should be called up in the create loop in lines 140-200 right before we call "facility_REST()".  

Before I do that I wanted to ask: Did you all stick some other code in there that already checks this list before creating a facility?

**Comment by jmineva** [comment]
@rburghol We do not have a check for these VAHydro facilities. 

I'm wondering if it even needs to be its own function. Could we just include a check for the facility in the facility_REST() function?

- We would just pull in the VAHydro list of facilities before the for loop
- then in the facility_REST() check if the ECHO_facilities_i matches a facility in the list 
- if it does match, skip the postFeature step and just retrieve the facility from VAHydro with getFeature
- if it does not match, continue on with the function as is

**Comment by rburghol** [comment]
Awesome. The only issue with facility_REST() is then we make that more multi-purpose than I would prefer, but I will try to make it straightforward and clean (and quick).  Thanks for the quick review and algorithm thoughts.

**Comment by rburghol** [comment]
This function also sets a number of data frames that are used later on, so don't think it can be disposed of just yet.

**Comment by rburghol** [comment]
This has been moved into a separate function to be run before using the standard function to add an ECHO facility via REST.
