### ISSUE TITLE
timeseries import function?

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/USGS_Consumptive_Use#80]
I just wanted to verify that you all haven't already written/replaced the timseries import function "ts_import()".  @jdkleiner @jmineva

**Comment by jdkleiner** [comment]
I have not!

**Comment by jmineva** [comment]
@rburghol Nope! That was the next big section to get through.

**Comment by rburghol** [comment]
Ok awesome - thanks to you both. Test importing underway in alpha. Seems like it is going well. Verified that code was handling the "Matched" facilities appropriately. Will keep you posted.
