### ISSUE TITLE
WUDR Project - Timeseries Export Script

### ISSUE THREAD

**Issue by jmineva** [HARPgroup/USGS_Consumptive_Use#88]
1.  [ ] Live > Alpha view
1. Add contextual filter to Annual display page & export
   - [x] remove filter criteria which restricts the ts value to that varkey
   - [ ] add ts relationship
   - [x] set default to wd_mgy
   - [ ] specify validation criteria
   - [ ] allow multiple values
      `- SQLSTATE[42804]: Datatype mismatch: 7 ERROR: argument of AND must be type boolean, not type record LINE 15: WHERE (( (dh_timeseries.varid = '1393', '305' ) )AND(( (dh_t... ^`
      - wd_mgy (cumulative) and dmr_ann_mgy (value) have two different datatypes
   - [ ] once multiple values can be entered as contextual filters, include a varkey field to show the ts variable type
   - to see discharge data, set bundle = transfer (in R script, filter for hydrocode starts with 'echo_%')
1. Add contextual filter to Monthly display page & export
1. R Script

**Comment by jmineva** [comment]
@rburghol @jdkleiner I ran into an issue when modifying map export view to allow multiple contextual filters. The contextual filter has the option to 'allow multiple values'. However, I get an error because the wd_mgy datatype = cumulative and dmr_ann_mgy datatype = value. And since they don't match, I don't think they can appear in the same column. Is changing one of those datatypes an issue (I don't quite know what 'cumulative' datatype means)?

However, the contextual filter does work now if I just supply the variable one at a time. If we can't change the datatype then no biggie!

**Comment by rburghol** [comment]
The column datatype is only descriptive, i.e., they both correspond to a numeric quantity.  Shouldn't afecct the contextual filters, though maybe the cfilter script needs to be smarter to handle multiples (unless the version you copied from mine does so already).  Are you getting an error?

**Comment by jmineva** [comment]
I vaguely remember that the column datatype is descriptive. I also no vaguely remember that pulling multiple comma separated contextual filters into R didn't jive well either. We were trying to pull multiple permit authorities/regs? 
  
@rburghol Forgot how I should send view names. Is this enough or too much?
admin/structure/views/view/ows_annual_report_map_exports/edit/page

Here's the validation criteria for the annual map export page:
```
if (function_exists('dh_varkey2varid')) {
  $varid = dh_varkey2varid($argument);
  $handler->argument = $varid;
} else {
  drupal_set_message("Cannot load function dh_varkey2varid(varkey)");
}
return true;
```

I found another type of validation criteria on another view (ts to prop):
```
$varid = dh_varkey2varid($argument);
if ($varid > 0) {
  $handler->argument = $varid;
  return TRUE;
} else {
  return FALSE;
}
```

**Comment by rburghol** [comment]
@jmineva the views information you provided is perfect :).  I will check this out when I get through my imports, and until then, I agree with your approach to just pull in the annual, then do a pull for the monthly in separate lines.
